# Generated by Django 4.2.3 on 2023-12-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_booking_guest_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='family_book',
            field=models.ImageField(blank=True, null=True, upload_to='images/famBook'),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='images/card_id'),
        ),
        migrations.AddField(
            model_name='room',
            name='extra_bed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
