# Generated by Django 4.2.3 on 2023-12-16 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_booking_family_book_remove_booking_id_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=255)),
                ('fingerprint', models.ImageField(blank=True, null=True, upload_to='images/fingerprint')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='dashboard.staff')),
            ],
        ),
    ]
